# Generated by Django 3.0 on 2019-12-14 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191215_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name', 'last_name'], 'permissions': (('can_modify_author', 'Create, update, and delete author'),)},
        ),
    ]
