# Generated by Django 3.0 on 2019-12-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191215_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_modify_book', 'Create, update, and delete book'),)},
        ),
    ]
